# Generated by Django 5.1.1 on 2024-10-08 07:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 10, 8, 7, 5, 43, 250173, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
    ]
